project:
  type: website
  output-dir: docs

website:
  title: "Ava Li"
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - about.qmd
      - text: "Data Viz"
        menu:
          - text: ""
            href: docs/gas.html
          - text: ""
            href: 


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full



