---
title: "U.S. Weekly Gas Prices"
description: Analysis of weekly gas prices data from TidyTuesday
author: Ava Li
date: September 27, 2026
format: html
code-fold: true
---
```{r,message=FALSE,warning=FALSE}
#| echo: false
library(tidyverse)
library(openintro)

weekly_gas_prices <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-07-01/weekly_gas_prices.csv')

weekly_gas <- weekly_gas_prices
```

## The Data
Retrieved from TidyTuesday:   
https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-07-01

The data is originally from the U.S. Energy Information Administration (EIA), which publishes average retail gasoline and diesel prices weekly.


### Basic Prices Overtime Comparison
```{r}
ggplot(weekly_gas, aes(x=date, y=price, color=fct_relevel(fuel, "gasoline", "diesel"))) +
  geom_line() +
  scale_color_manual(values = c("gasoline" = "#438eff", "diesel" = "#f6ba21")) +
  labs(title = "Fuel Price Overtime", color = "Fuel")
```

<!--
```{r}
ggplot(weekly_gas, aes(x=date, y=price, color=fuel)) +
  geom_line() + 
  facet_wrap(~fuel) + 
  labs(title = "Fuel Price Overtime by Fuel")
```
-->
<!--
Prices by Grade (ALL)
```{r}
ggplot(weekly_gas, aes(x=date, y=price, color=grade)) +
  geom_line() + 
  facet_wrap(~grade) +
  labs( title = "Price by Grade")
```
```{r}
ggplot(weekly_gas, aes(x=date, y=price, color=grade)) +
  geom_line() + 
  facet_grid(~grade) + 
  labs(title = "Price by Grade")
```
-->


### Prices by Fuel Type, Grade, and Formulation
```{r}
weekly_gas |> 
  filter(fuel == "gasoline") |> 
  ggplot(aes(x=date, y=price, color=grade)) +
    geom_line() + 
    facet_wrap(~grade) + 
    labs(title = "Prices for Gasoline by Grade")
```

```{r}
weekly_gas|> 
  filter(fuel == "diesel") |> 
  ggplot( aes(x=date, y=price, color=grade)) +
    geom_line() + 
    facet_wrap(~grade) + 
    labs(title = "Prices for Diesel by Grade")
```

```{r}
weekly_gas |> 
  filter(fuel == "gasoline") |> 
  ggplot(aes(x=date, y=price, color=formulation)) +
    geom_line() + 
    facet_wrap(~grade) + 
    labs(
    title = "Prices by Formulation", x = "Date", y= "Price",  color = "Formulation" )
```


### Price Distribution
```{r}
ggplot(weekly_gas, aes(x=price, fill = fct_relevel(fuel, "gasoline", "diesel"))) +
    geom_histogram(binwidth = 0.1) + 
    labs(title = "Distribution of Price Changes by Fuel", fill = "Fuel")
```

```{r}
ggplot(weekly_gas, aes(x=price, color = grade)) +
    geom_boxplot() + 
    facet_wrap(~fuel) +
    labs(title = "Distribution of Price Changes by Grade")
```